### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by andrecbarros** [beta-tester/RPi-PXE-Server#11]
Can you post here the patch you applied to kaspersky rescue disk?

**Comment by beta-tester** [comment]
here the patch as attachement:
[init.patch.zip](https://github.com/beta-tester/RPi-PXE-Server/files/2721289/init.patch.zip)

you can find the patch also on this thread: https://github.com/beta-tester/RPi-PXE-Server/issues/10#issuecomment-449555361
(there is also an already patched initrd.xz)

or https://forum.kaspersky.com/index.php?/topic/397563-krd-2018-pxe/&tab=comments#comment-2843816

BTW: the project RPi-PXE-Server will download the patched initrd.xz file automatically, when you install the Kaspersky Rescue Disk by the install script... so there is no need to apply the patch by yourself.

or are you from Kaspersky Laps and want to include the patch to the Kaspersky Rescue Disk release?

**Comment by andrecbarros** [comment]
No relation with Kaspersky, just like their antivirus product and have to administer some PXE servers for backup services and emergency happenings.

Thanks for sharing!

**Comment by beta-tester** [comment]
it was now pathed by kaspersky...
should now work without the extra init file.
see https://community.kaspersky.com/kaspersky-rescue-disk-78/please-fix-init-file-of-the-rescure-dvd-for-proper-pxe-boot-970
