### ISSUE TITLE
Add POP!_OS to the list

### ISSUE THREAD

**Issue by squadramunter** [beta-tester/RPi-PXE-Server#26]
I saw more info was needed.

Just google pop!_os iso and you go to this page.

https://system76.com/pop

Nvidia Version

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/nvidia/10/pop-os_19.04_amd64_nvidia_10.iso

Intel/AMD version

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/intel/10/pop-os_19.04_amd64_intel_10.iso

**Comment by beta-tester** [comment]
duplicate of #25
