### ISSUE TITLE
about ReadMe.md

### ISSUE THREAD

**Issue by souhaiebtar** [beta-tester/RPi-PXE-Server#29]
what software have you used to create the schematic overview?

**Comment by beta-tester** [comment]
no software... it's kind of ASCII-art...
it is handmade in a normal texteditor setted up to use monospace font
and picked and placed the needed characters.

https://en.wikipedia.org/wiki/Box-drawing_character

then i cut and paste the "drawing" into the readme.md
to keep the constant spacing, i put the "drawing" in to code block.

```
     _
    / )
   / /___
__/  (___)
   _/(___)
___  (___)
   \_(__)

```
