### ISSUE TITLE
New Kali Linux

### ISSUE THREAD

**Issue by Mightyretro** [beta-tester/RPi-PXE-Server#41]
Hi,

i haven't checked back in a while and notice you update is quite a bit :)

could you add Kali Purple:
https://www.kali.org/get-kali/#kali-platforms

Btw i notice you have USB storage to where you can store and launch iso right? for example Windows ISO?

// Kind Regards

**Comment by beta-tester** [comment]
> could you add Kali Purple:

is Kali Purple a Live image or just an installer image?

you can try it by yourself. just change the url of the Kali live iso to the kali purple installer iso in the `p2-include-url` file and see if it can boot into and meets your needs.
```sh
KALI_X64=kali-x64
##KALI_X64_URL=https://cdimage.kali.org/current/kali-linux-2023.2-live-amd64.iso
KALI_X64_URL=https://cdimage.kali.org/current/kali-linux-2023.2a-installer-purple-amd64.iso
KALI_X64_SUM=https://cdimage.kali.org/current/SHA256SUMS
KALI_X64_SUM_TYPE=sha256
```

> Btw i notice you have USB storage to where you can store and launch iso right?

right, you can store iso images to the usb storage instead to the internal SD card.
modify the variable in the `p2-include-var` file to the path, where your USB storage is permanently mounted:
```
DST_ROOT=/srv
```


> for example Windows ISO?

yes, but only the Windows PE (Preinstallation Environment) is able to boot over the network - you have to make your own Windows boot media by hand. look at the wiki section [Create a WinPE ISO](https://github.com/beta-tester/RPi-PXE-Server/wiki/Create-a-WinPE-ISO).

the normal windows setup will not boot or find the installation files unless you mount the files manually (for example via samba / windows share) and start the setup from the console.
